/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Images {
  created_at: Generated<Timestamp>;
  file_key: string;
  id: Generated<number>;
  mime_type: string;
  original_name: string;
  size: Int8;
  updated_at: Generated<Timestamp>;
  user_id: number | null;
}

export interface Items {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  name: string;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  images: Images;
  items: Items;
  users: Users;
}
