/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ChallengeAnswers {
  challenge_id: number;
  choice_id: number;
  id: Generated<number>;
  question_id: number;
}

export interface Challenges {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_first_attempt: boolean;
  quiz_set_id: number;
  score: number;
  user_id: number;
}

export interface Choices {
  choice_text: string;
  id: Generated<number>;
  is_correct: boolean;
  question_id: number;
}

export interface Images {
  created_at: Generated<Timestamp>;
  file_key: string;
  id: Generated<number>;
  mime_type: string;
  original_name: string;
  size: Int8;
  updated_at: Generated<Timestamp>;
  user_id: number | null;
}

export interface Items {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Questions {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  question_text: string;
  quiz_set_id: number;
  updated_at: Generated<Timestamp>;
}

export interface QuizSets {
  author_id: number;
  category: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  is_public: Generated<boolean>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  name: string;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  challenge_answers: ChallengeAnswers;
  challenges: Challenges;
  choices: Choices;
  images: Images;
  items: Items;
  questions: Questions;
  quiz_sets: QuizSets;
  users: Users;
}
